import json
import logging

from fastapi import HTTPException

from utils.bedrock_client import invoke_bedrock
from utils.dynamo_client import get_all_service_configs, get_service_config, get_session
from utils.service_mapper import (
    get_provider_label,
    get_provider_service_name,
    get_terraform_resources,
    normalize_provider,
)

logger = logging.getLogger(__name__)

TERRAFORM_PROMPT = """
Generate a complete Terraform configuration for {provider} {service}.

Company context:
- Industry: {industry}
- Compliance: {frameworks}
- Security weight: {security_weight}

Configuration to implement:
{config_values_json}

Reasoning for each field (use as inline HCL comments):
{config_reasons_json}

Rules:
1. Use correct Terraform resource types:
{resource_mappings}

2. Add compliance reason as comment ABOVE each field:
   # REASON: {reason}

3. Add this exact header at very top:
   # ============================================
   # Generated by NIMBUS1000 Cloud Security Copilot
   # Company Industry: {industry}
   # Compliance Frameworks: {frameworks}
   # Security Weight: {security_weight}
   # ============================================

4. Add this provider block:
{provider_block}

5. Resource name always "main"
6. Return ONLY valid HCL - no markdown, no backticks
"""


def _normalize_config(raw_config: dict) -> tuple[dict, dict]:
    values = {}
    reasons = {}
    for field_id, entry in raw_config.items():
        if isinstance(entry, dict) and "value" in entry:
            values[field_id] = entry["value"]
            reasons[field_id] = entry.get("reason", "")
        else:
            values[field_id] = entry
            reasons[field_id] = ""
    return values, reasons


def _serialize_value(value):
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return json.dumps(value)
    return json.dumps(value)


def _provider_block(provider: str) -> list[str]:
    provider = normalize_provider(provider)
    if provider == "azure":
        return [
            'provider "azurerm" {',
            "  features {}",
            "}",
            'variable "resource_group" { default = "nimbus-rg" }',
            "",
        ]
    if provider == "gcp":
        return [
            'provider "google" {',
            "  project = var.gcp_project",
            "  region  = var.gcp_region",
            "}",
            'variable "gcp_project" { default = "nimbus-project" }',
            'variable "gcp_region" { default = "us-central1" }',
            "",
        ]
    return [
        'provider "aws" { region = var.aws_region }',
        'variable "aws_region" { default = "us-east-1" }',
        "",
    ]


def _header(industry: str, frameworks: str, security_weight) -> list[str]:
    return [
        "# ============================================",
        "# Generated by NIMBUS1000 Cloud Security Copilot",
        f"# Company Industry: {industry}",
        f"# Compliance Frameworks: {frameworks}",
        f"# Security Weight: {security_weight}",
        "# ============================================",
        "",
    ]


def _resource_mappings(service: str, provider: str) -> str:
    resources = get_terraform_resources(service, provider)
    return "\n".join(f"   - {service} -> {resource}" for resource in resources)


def _field_name(field_id: str) -> str:
    return field_id.replace(".", "_").replace("-", "_")


def _render_service_block(service: str, provider: str, values: dict, reasons: dict) -> list[str]:
    blocks = []
    for resource_type in get_terraform_resources(service, provider):
        blocks.append(f'resource "{resource_type}" "main" {{')
        for field_id, value in values.items():
            blocks.append(f"  # REASON: {reasons.get(field_id, 'security best practice')}")
            blocks.append(f"  {_field_name(field_id)} = {_serialize_value(value)}")
        blocks.append("}")
        blocks.append("")
    return blocks


def _fallback_hcl(provider: str, industry: str, frameworks: str, security_weight, configs: dict[str, tuple[dict, dict]]) -> str:
    lines = _header(industry, frameworks, security_weight)
    lines.extend(_provider_block(provider))
    for service, (values, reasons) in configs.items():
        lines.extend(_render_service_block(service, provider, values, reasons))
    return "\n".join(lines).strip()


def _strip_markdown_fences(content: str) -> str:
    cleaned = content.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        cleaned = "\n".join(lines[1:-1]).strip()
    return cleaned


async def generate_terraform(session_id, service=None, provider="aws") -> str:
    provider = normalize_provider(provider)
    try:
        session = get_session(session_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Session not found. Start a new session.")

    if service:
        canonical_service = get_provider_service_name(service, provider)
        raw_config = get_service_config(session_id, canonical_service)
        if not raw_config:
            raise HTTPException(
                status_code=400,
                detail=f"No config found for {canonical_service}. Generate config first.",
            )
        raw_configs = {canonical_service: raw_config}
    else:
        raw_configs = get_all_service_configs(session_id)
        if not raw_configs:
            raise HTTPException(status_code=400, detail="No configured services found. Generate config first.")

    normalized_configs = {}
    for current_service, raw_service_config in raw_configs.items():
        values, reasons = _normalize_config(raw_service_config)
        if not values:
            raise ValueError(
                f"Generated config for {current_service} has no field values. Regenerate the config before exporting Terraform."
            )
        normalized_configs[current_service] = (values, reasons)

    profile = session.get("companyProfile", {})
    industry = profile.get("industry", "other")
    frameworks = ", ".join(profile.get("complianceFrameworks", ["none"]))
    security_weight = session.get("computedWeights", {}).get("security", 0)

    if len(normalized_configs) == 1:
        current_service, (config_values, config_reasons) = next(iter(normalized_configs.items()))
        prompt = TERRAFORM_PROMPT
        replacements = {
            "{provider}": get_provider_label(provider),
            "{service}": current_service,
            "{industry}": industry,
            "{frameworks}": frameworks,
            "{security_weight}": str(security_weight),
            "{config_values_json}": json.dumps(config_values, indent=2),
            "{config_reasons_json}": json.dumps(config_reasons, indent=2),
            "{resource_mappings}": _resource_mappings(current_service, provider),
            "{provider_block}": "\n".join(_provider_block(provider)).strip(),
        }
        for key, value in replacements.items():
            prompt = prompt.replace(key, value)
        try:
            content = invoke_bedrock(prompt)
        except Exception as exc:
            logger.warning("Terraform generation fell back to deterministic HCL for %s: %s", current_service, exc)
            content = _fallback_hcl(provider, industry, frameworks, security_weight, normalized_configs)
        cleaned = _strip_markdown_fences(content)
        if "resource" not in cleaned:
            cleaned = _fallback_hcl(provider, industry, frameworks, security_weight, normalized_configs)
        return cleaned

    try:
        combined_prompt = TERRAFORM_PROMPT
        replacements = {
            "{provider}": get_provider_label(provider),
            "{service}": "multiple services",
            "{industry}": industry,
            "{frameworks}": frameworks,
            "{security_weight}": str(security_weight),
            "{config_values_json}": json.dumps(
                {service_name: values for service_name, (values, _) in normalized_configs.items()},
                indent=2,
            ),
            "{config_reasons_json}": json.dumps(
                {service_name: reasons for service_name, (_, reasons) in normalized_configs.items()},
                indent=2,
            ),
            "{resource_mappings}": "\n".join(
                _resource_mappings(service_name, provider) for service_name in normalized_configs
            ),
            "{provider_block}": "\n".join(_provider_block(provider)).strip(),
        }
        for key, value in replacements.items():
            combined_prompt = combined_prompt.replace(key, value)
        content = invoke_bedrock(combined_prompt)
        cleaned = _strip_markdown_fences(content)
        if "resource" in cleaned:
            return cleaned
    except Exception as exc:
        logger.warning("Combined Terraform generation fell back to deterministic HCL: %s", exc)

    return _fallback_hcl(provider, industry, frameworks, security_weight, normalized_configs)
