import json
import logging

from fastapi import HTTPException

from utils.bedrock_client import invoke_bedrock
from utils.dynamo_client import get_all_service_configs, get_service_config, get_service_provider, get_service_providers, get_session
from utils.service_mapper import (
    get_provider_label,
    get_provider_service_name,
    get_terraform_resources,
    normalize_provider,
)

logger = logging.getLogger(__name__)

TERRAFORM_PROMPT = """<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are a senior Terraform engineer writing production-ready, security-hardened HCL for regulated industries. Return ONLY valid HCL — no markdown fences, no backticks, no explanation before or after the code.
<|eot_id|><|start_header_id|>user<|end_header_id|>

Generate a complete Terraform configuration for {provider} {service}.

Company context:
- Industry: {industry}
- Compliance frameworks: {frameworks}
- Security weight: {security_weight}

Configuration values to implement:
{config_values_json}

Compliance reasons for each field (use these as inline HCL comments):
{config_reasons_json}

Terraform resource type mappings to use:
{resource_mappings}

Provider block to include:
{provider_block}

Requirements:
1. Use the exact resource types listed in the mappings above. Resource name must always be "main".
2. Add an inline comment ABOVE each field using the reason from config_reasons_json:
   # REASON: <reason text>
3. Add this exact header at the very top of the file:
   # ============================================
   # Generated by NIMBUS1000 Cloud Security Copilot
   # Industry: {industry}
   # Compliance: {frameworks}
   # Security Weight: {security_weight}
   # ============================================
4. Add terraform version constraints block:
   terraform {{
     required_version = ">= 1.5"
     required_providers {{
       <provider_name> = {{
         source  = "<provider_source>"
         version = "~> <latest_stable>"
       }}
     }}
   }}
5. Boolean values: use true/false (lowercase). String values: use quoted strings.
6. Return ONLY valid HCL. No markdown backticks, no explanation.

<|eot_id|><|start_header_id|>assistant<|end_header_id|>
"""

PROVIDER_VERSIONS = {
    "aws": ("aws", "hashicorp/aws", "5.0"),
    "azure": ("azurerm", "hashicorp/azurerm", "3.0"),
    "gcp": ("google", "hashicorp/google", "5.0"),
}


def _normalize_config(raw_config: dict) -> tuple[dict, dict]:
    values = {}
    reasons = {}
    for field_id, entry in raw_config.items():
        if isinstance(entry, dict) and "value" in entry:
            values[field_id] = entry["value"]
            reasons[field_id] = entry.get("reason", "")
        else:
            values[field_id] = entry
            reasons[field_id] = ""
    return values, reasons


def _serialize_value(value):
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return json.dumps(value)
    return json.dumps(value)


def _provider_block(provider: str) -> list[str]:
    provider = normalize_provider(provider)
    name, source, version = PROVIDER_VERSIONS.get(provider, ("aws", "hashicorp/aws", "5.0"))
    tf_block = [
        "terraform {",
        '  required_version = ">= 1.5"',
        "  required_providers {",
        f'    {name} = {{',
        f'      source  = "{source}"',
        f'      version = "~> {version}"',
        "    }",
        "  }",
        "}",
        "",
    ]
    if provider == "azure":
        return tf_block + [
            'provider "azurerm" {',
            "  features {}",
            "}",
            'variable "resource_group" { default = "nimbus-rg" }',
            "",
        ]
    if provider == "gcp":
        return tf_block + [
            'provider "google" {',
            "  project = var.gcp_project",
            "  region  = var.gcp_region",
            "}",
            'variable "gcp_project" { default = "nimbus-project" }',
            'variable "gcp_region"  { default = "us-central1" }',
            "",
        ]
    return tf_block + [
        'provider "aws" {',
        "  region = var.aws_region",
        "}",
        'variable "aws_region" { default = "us-east-1" }',
        "",
    ]


def _header(industry: str, frameworks: str, security_weight) -> list[str]:
    return [
        "# ============================================",
        "# Generated by NIMBUS1000 Cloud Security Copilot",
        f"# Industry: {industry}",
        f"# Compliance: {frameworks}",
        f"# Security Weight: {security_weight}",
        "# ============================================",
        "",
    ]


def _resource_mappings(service: str, provider: str) -> str:
    resources = get_terraform_resources(service, provider)
    return "\n".join(f"   - {service} -> {resource}" for resource in resources)


def _field_name(field_id: str) -> str:
    return field_id.replace(".", "_").replace("-", "_")


def _render_service_block(service: str, provider: str, values: dict, reasons: dict) -> list[str]:
    blocks = []
    for resource_type in get_terraform_resources(service, provider):
        blocks.append(f'resource "{resource_type}" "main" {{')
        for field_id, value in values.items():
            blocks.append(f"  # REASON: {reasons.get(field_id, 'security best practice')}")
            blocks.append(f"  {_field_name(field_id)} = {_serialize_value(value)}")
        blocks.append("}")
        blocks.append("")
    return blocks

def _strip_markdown_fences(content: str) -> str:
    cleaned = content.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        cleaned = "\n".join(lines[1:-1]).strip()
    return cleaned


async def generate_terraform(session_id, service=None, provider="aws") -> str:
    provider = normalize_provider(provider)
    try:
        session = get_session(session_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Session not found. Start a new session.")

    if service:
        canonical_service = get_provider_service_name(service, provider)
        raw_config = get_service_config(session_id, canonical_service)
        if not raw_config:
            raise HTTPException(
                status_code=400,
                detail=f"No config found for {canonical_service}. Generate config first.",
            )
        raw_configs = {canonical_service: raw_config}
        service_provider_map = {canonical_service: get_service_provider(session_id, canonical_service) or provider}
    else:
        raw_configs = get_all_service_configs(session_id)
        if not raw_configs:
            raise HTTPException(status_code=400, detail="No configured services found. Generate config first.")
        service_provider_map = get_service_providers(session_id) or {}

    normalized_configs = {}
    for current_service, raw_service_config in raw_configs.items():
        values, reasons = _normalize_config(raw_service_config)
        if not values:
            raise ValueError(
                f"Generated config for {current_service} has no field values. Regenerate the config before exporting Terraform."
            )
        normalized_configs[current_service] = (
            service_provider_map.get(current_service, provider),
            values,
            reasons,
        )

    profile = session.get("companyProfile", {})
    industry = profile.get("industry", "other")
    frameworks = ", ".join(profile.get("complianceFrameworks", ["none"]))
    security_weight = session.get("computedWeights", {}).get("security", 0)

    if len(normalized_configs) == 1:
        current_service, (service_provider, config_values, config_reasons) = next(iter(normalized_configs.items()))
        prompt = TERRAFORM_PROMPT
        replacements = {
            "{provider}": get_provider_label(service_provider),
            "{service}": current_service,
            "{industry}": industry,
            "{frameworks}": frameworks,
            "{security_weight}": str(security_weight),
            "{config_values_json}": json.dumps(config_values, indent=2),
            "{config_reasons_json}": json.dumps(config_reasons, indent=2),
            "{resource_mappings}": _resource_mappings(current_service, service_provider),
            "{provider_block}": "\n".join(_provider_block(service_provider)).strip(),
        }
        for key, value in replacements.items():
            prompt = prompt.replace(key, value)
        content = invoke_bedrock(prompt)
        cleaned = _strip_markdown_fences(content)
        if "resource" not in cleaned:
            raise ValueError(f"Terraform generation for {current_service} did not return valid resource blocks.")
        return cleaned

    combined_prompt = TERRAFORM_PROMPT
    replacements = {
        "{provider}": "multi-cloud",
        "{service}": "multiple services",
        "{industry}": industry,
        "{frameworks}": frameworks,
        "{security_weight}": str(security_weight),
        "{config_values_json}": json.dumps(
            {service_name: values for service_name, (_, values, _) in normalized_configs.items()},
            indent=2,
        ),
        "{config_reasons_json}": json.dumps(
            {service_name: reasons for service_name, (_, _, reasons) in normalized_configs.items()},
            indent=2,
        ),
        "{resource_mappings}": "\n".join(
            _resource_mappings(service_name, current_provider)
            for service_name, (current_provider, _, _) in normalized_configs.items()
        ),
        "{provider_block}": "\n\n".join(
            "\n".join(_provider_block(current_provider)).strip()
            for current_provider in list(dict.fromkeys(provider_name for provider_name, _, _ in normalized_configs.values()))
        ),
    }
    for key, value in replacements.items():
        combined_prompt = combined_prompt.replace(key, value)
    content = invoke_bedrock(combined_prompt)
    cleaned = _strip_markdown_fences(content)
    if "resource" not in cleaned:
        raise ValueError("Combined Terraform generation did not return valid resource blocks.")
    return cleaned
