export const C = {
  navy:        '#232F3E',
  orange:      '#FF9900',
  orangeHover: '#EC7211',
  green:       '#1D8348',
  red:         '#C0392B',
  amber:       '#D68910',
  purple:      '#6C3483',
  purpleBg:    '#F4ECF7',
  bgBase:      '#FFFFFF',
  bgPanel:     '#F1F3F3',
  bgElevated:  '#FFFFFF',
  border:      '#D5DBDB',
  borderLight: '#AAB7B8',
  textPrimary: '#16191F',
  textMuted:   '#545B64',
  textFaint:   '#879596',
}

export const css = {
  panelHeader: {
    padding: '20px 24px 16px',
    background: C.navy,
    borderBottom: `1px solid ${C.border}`,
    flexShrink: 0,
  },
  headerLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: C.orange,
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: '#FFFFFF',
    margin: 0,
  },
  fieldCard: {
    background: C.bgElevated,
    border: `1px solid ${C.border}`,
    borderRadius: 4,
    padding: '16px 20px',
    marginBottom: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  tailoredBadge: {
    background: C.purpleBg,
    color: C.purple,
    fontSize: 10,
    padding: '2px 8px',
    borderRadius: 99,
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  bubble: (role) => ({
    padding: '10px 12px',
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.6,
    color: C.textPrimary,
    background: role === 'user' ? C.bgPanel : '#FFF8F0',
    border: `1px solid ${role === 'user' ? C.border : '#F5CBA7'}`,
    marginBottom: 8,
  }),
  roleLabel: (role) => ({
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase',
    color: role === 'user' ? C.textFaint : C.navy,
    marginBottom: 4,
    marginLeft: 2,
  }),
}
